/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Ris3TwO
 */
public class RegistroPeaton extends javax.swing.JDialog {

    /**
     * Creates new form RegistroPeaton
     */
    public RegistroPeaton(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPlacaIcono = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblPlaca = new javax.swing.JLabel();
        lblPuestoNumero = new javax.swing.JLabel();
        lblPlaca1 = new javax.swing.JLabel();
        lblPlacaIcono1 = new javax.swing.JLabel();
        txtCedulaPeaton = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtNombrePeaton = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblPlacaIcono2 = new javax.swing.JLabel();
        lblPlaca2 = new javax.swing.JLabel();
        lblPlaca3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtApellidoPeaton = new javax.swing.JTextField();
        lblPlacaIcono3 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtAptoAVisitar = new javax.swing.JTextField();
        lblPlaca4 = new javax.swing.JLabel();
        lblPlacaIcono4 = new javax.swing.JLabel();
        cmbTipoPeaton = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(102, 102, 102));
        btnCerrar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Multiply_32px.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Multiply._32px.png"))); // NOI18N
        btnCerrar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Multiply_32px.png"))); // NOI18N
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 40, 40));

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 153, 0));
        lblTitulo.setText("Registrar Peatón");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 690, 10));

        lblPlacaIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man-11.png"))); // NOI18N
        jPanel1.add(lblPlacaIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jSeparator2.setOpaque(true);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 230, 10));

        lblPlaca.setBackground(new java.awt.Color(0, 0, 0));
        lblPlaca.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPlaca.setText("Tipo de Peatón:");
        jPanel1.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        lblPuestoNumero.setBackground(new java.awt.Color(0, 0, 0));
        lblPuestoNumero.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPuestoNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuestoNumero.setText("DATOS DEL PEATÓN");
        jPanel1.add(lblPuestoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 687, -1));

        lblPlaca1.setBackground(new java.awt.Color(0, 0, 0));
        lblPlaca1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPlaca1.setText("Cédula:");
        jPanel1.add(lblPlaca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        lblPlacaIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id-card-3.png"))); // NOI18N
        jPanel1.add(lblPlacaIcono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        txtCedulaPeaton.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCedulaPeaton.setForeground(new java.awt.Color(153, 153, 153));
        txtCedulaPeaton.setBorder(null);
        jPanel1.add(txtCedulaPeaton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 180, 30));

        jSeparator3.setOpaque(true);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 230, 10));

        txtNombrePeaton.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombrePeaton.setForeground(new java.awt.Color(153, 153, 153));
        txtNombrePeaton.setBorder(null);
        jPanel1.add(txtNombrePeaton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 180, 30));

        jSeparator4.setOpaque(true);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 230, 10));

        lblPlacaIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resume.png"))); // NOI18N
        jPanel1.add(lblPlacaIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        lblPlaca2.setBackground(new java.awt.Color(0, 0, 0));
        lblPlaca2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPlaca2.setText("Nombres:");
        jPanel1.add(lblPlaca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        lblPlaca3.setBackground(new java.awt.Color(0, 0, 0));
        lblPlaca3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPlaca3.setText("Apellidos:");
        jPanel1.add(lblPlaca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jSeparator5.setOpaque(true);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 230, 10));

        txtApellidoPeaton.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtApellidoPeaton.setForeground(new java.awt.Color(153, 153, 153));
        txtApellidoPeaton.setBorder(null);
        jPanel1.add(txtApellidoPeaton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 180, 30));

        lblPlacaIcono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resume.png"))); // NOI18N
        jPanel1.add(lblPlacaIcono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jSeparator6.setOpaque(true);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 230, 10));

        txtAptoAVisitar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtAptoAVisitar.setForeground(new java.awt.Color(153, 153, 153));
        txtAptoAVisitar.setBorder(null);
        jPanel1.add(txtAptoAVisitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 180, 30));

        lblPlaca4.setBackground(new java.awt.Color(0, 0, 0));
        lblPlaca4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPlaca4.setText("Nº de Apto a Visitar:");
        jPanel1.add(lblPlaca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        lblPlacaIcono4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/house.png"))); // NOI18N
        jPanel1.add(lblPlacaIcono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        cmbTipoPeaton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cmbTipoPeaton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Visitante", "Trabajador" }));
        cmbTipoPeaton.setToolTipText("Seleccione tipo de peaton, si es visitante o trabajador");
        jPanel1.add(cmbTipoPeaton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 180, -1));

        btn_save.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right 4.png"))); // NOI18N
        btn_save.setText("Registrar");
        btn_save.setBorder(null);
        btn_save.setBorderPainted(false);
        btn_save.setContentAreaFilled(false);
        btn_save.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right 3.png"))); // NOI18N
        btn_save.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right 3.png"))); // NOI18N
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, 40));

        btnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/multiply 1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/multiply 2.png"))); // NOI18N
        btnCancelar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/multiply 2.png"))); // NOI18N
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPeaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPeaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPeaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPeaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroPeaton dialog = new RegistroPeaton(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    public javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmbTipoPeaton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPlaca1;
    private javax.swing.JLabel lblPlaca2;
    private javax.swing.JLabel lblPlaca3;
    private javax.swing.JLabel lblPlaca4;
    private javax.swing.JLabel lblPlacaIcono;
    private javax.swing.JLabel lblPlacaIcono1;
    private javax.swing.JLabel lblPlacaIcono2;
    private javax.swing.JLabel lblPlacaIcono3;
    private javax.swing.JLabel lblPlacaIcono4;
    private javax.swing.JLabel lblPuestoNumero;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellidoPeaton;
    private javax.swing.JTextField txtAptoAVisitar;
    private javax.swing.JTextField txtCedulaPeaton;
    private javax.swing.JTextField txtNombrePeaton;
    // End of variables declaration//GEN-END:variables
}
